### ISSUE TITLE
Running with *no* parameters at all crashes the command line parser

### ISSUE THREAD

**Issue by marcscheuner-bfh** [MatthiWare/CommandLineParser.Core#12]
Starting the console app without any parameters, the command line parser crashes:

> System.ArgumentOutOfRangeException
>   HResult=0x80131502
>   Message=Index was out of range. Must be non-negative and less than the size of the collection.
> Parameter name: index
>   Source=mscorlib
>   StackTrace:
>    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
>    at System.Collections.Generic.List`1.get_Item(Int32 index)
>    at MatthiWare.CommandLine.Core.Parsing.ArgumentManager.SetArgumentUsed(Int32 idx, ICommandLineCommand cmd)
>    at MatthiWare.CommandLine.Core.Parsing.ArgumentManager.Parse(IEnumerable`1 list)
>    at MatthiWare.CommandLine.Core.Parsing.ArgumentManager..ctor(String[] args, ICollection`1 commands, ICollection`1 options)
>    at MatthiWare.CommandLine.CommandLineParser`1.Parse(String[] args)
>

**Comment by marcscheuner-bfh** [comment]
Thanks - works like a charm now! Great stuff
